// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWdim7ty9sSnW3HJ4SP1Dy8Do54ZZesto',
    appId: '1:1000403319937:web:9149006770437ee872e180',
    messagingSenderId: '1000403319937',
    projectId: 'chatapp-d1b91',
    authDomain: 'chatapp-d1b91.firebaseapp.com',
    storageBucket: 'chatapp-d1b91.appspot.com',
    measurementId: 'G-N0N78R0DNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp-zDuaPrgcF7tX_7RRh4KIynrT3mmwCg',
    appId: '1:1000403319937:android:c4e1cadb5c495a4572e180',
    messagingSenderId: '1000403319937',
    projectId: 'chatapp-d1b91',
    storageBucket: 'chatapp-d1b91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh-OWJLDIoi5yaVu0TXZrjTM7DHFBL8hE',
    appId: '1:1000403319937:ios:831852e5064ff4d372e180',
    messagingSenderId: '1000403319937',
    projectId: 'chatapp-d1b91',
    storageBucket: 'chatapp-d1b91.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh-OWJLDIoi5yaVu0TXZrjTM7DHFBL8hE',
    appId: '1:1000403319937:ios:8cce8e172913dc3872e180',
    messagingSenderId: '1000403319937',
    projectId: 'chatapp-d1b91',
    storageBucket: 'chatapp-d1b91.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
